-- Lesson 3: Create a Simple Product
-- Module 11: Payments: Simple Invoices, Products, and Payment Links
-- Generated by Course Content Creator Skill

-- Insert/Update Lesson 3: Create a Simple Product
-- Module 11: Payments: Simple Invoices, Products, and Payment Links
-- Using color blocks, icons, horizontal cards, and better visual hierarchy

DO $$
DECLARE
  v_module_id UUID;
  v_lesson_id UUID;
BEGIN
  -- Get Module by week number
  SELECT id INTO v_module_id FROM public.training_modules WHERE week_number = 11 LIMIT 1;
  
  IF v_module_id IS NULL THEN
    RAISE NOTICE 'Module 11 not found';
    RETURN;
  END IF;

  -- Check if lesson exists
  SELECT id INTO v_lesson_id 
  FROM public.lessons 
  WHERE slug = 'create-simple-product' AND module_id = v_module_id;
  
  IF v_lesson_id IS NULL THEN
    -- Insert new lesson
    INSERT INTO public.lessons (
      module_id, 
      lesson_number, 
      title, 
      slug, 
      content, 
      is_published, 
      sort_order,
      created_at,
      updated_at
    ) VALUES (
      v_module_id,
      3,
      'Create a Simple Product',
      'create-simple-product',
      '<div class="space-y-8">
  <!-- Learning Goal -->
  <div class="bg-gradient-to-r from-amber-500 to-orange-500 rounded-2xl p-6 text-white shadow-lg">
    <div class="flex items-center gap-3 mb-3">
      <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-lg font-bold">Learning Goal</h3>
    </div>
    <p class="text-white/90 text-lg">Create a reusable one-time service product with a clear name, description, and price.</p>
  </div>

  <!-- Step 1: Open Products -->
  <div class="bg-gradient-to-br from-slate-50 to-blue-50 rounded-2xl p-6 border border-blue-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 1: Open Products</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Navigate to Products</h4>
          <p class="text-sm text-slate-600">Go to Payments → Products. Select Create Product. Choose the standard product option.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Step 2: Add Product Information -->
  <div class="bg-gradient-to-br from-slate-50 to-cyan-50 rounded-2xl p-6 border border-cyan-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-cyan-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 2: Add Product Information</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Name and Description</h4>
          <p class="text-sm text-slate-600">Name: 90-Minute Strategy Session. Description: A focused 90-minute session to review one business challenge and agree on the next actions.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Image (Optional)</h4>
          <p class="text-sm text-slate-600">Add an image only if it helps the buyer recognize the offer.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Keep Names Clear</h4>
          <p class="text-sm text-slate-600">Avoid internal codes or vague labels that a buyer will not understand.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Step 3: Add the Price -->
  <div class="bg-gradient-to-br from-slate-50 to-green-50 rounded-2xl p-6 border border-green-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 3: Add the Price</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Price Settings</h4>
          <p class="text-sm text-slate-600">Payment type: One-time. Amount: $495.00 (or your selected price). Currency: The currency used by the connected account.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Recurring Prices</h4>
          <p class="text-sm text-slate-600">Create recurring prices only after deciding billing frequency, start date, cancellation terms, and what the customer receives each period.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Step 4: Review and Save -->
  <div class="bg-gradient-to-br from-slate-50 to-green-50 rounded-2xl p-6 border border-green-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 4: Review and Save</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Optional Settings</h4>
          <p class="text-sm text-slate-600">Check taxes, product statement description, quantity, online-store visibility, inventory (if physical item).</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Don''t Enable Unnecessary Settings</h4>
          <p class="text-sm text-slate-600">Do not turn on a setting simply because it is available. It should match how this offer is sold and delivered.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Save and Inspect</h4>
          <p class="text-sm text-slate-600">Save the product, then reopen it and verify: name is correct, description is clear, amount and currency are correct, price is one-time, tax settings match, product is active.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Naming Examples -->
  <div class="bg-gradient-to-br from-slate-50 to-amber-50 rounded-2xl p-6 border border-amber-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Naming Examples</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Clear Names</h4>
          <p class="text-sm text-slate-600">Coach: Leadership Coaching Session — 60 Minutes. Consultant: Operations Review — Half Day. Speaker: Virtual Keynote — 45 Minutes.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Weak Names</h4>
          <p class="text-sm text-slate-600">Avoid vague names like: Coaching, Consulting Work, Speaking, Training, Plan A.</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Point -->
  <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-6 border-l-4 border-amber-400">
    <div class="flex items-start gap-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
      </div>
      <div>
        <h3 class="text-lg font-bold text-amber-900 mb-2">Key Point</h3>
        <p class="text-amber-800 text-lg">Create a clear, descriptive product with the correct price and payment type. Save and inspect before using it in invoices or payment links.</p>
      </div>
    </div>
  </div>

  <!-- Action Steps -->
  <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border-2 border-emerald-200">
    <div class="flex items-center gap-3 mb-5">
      <div class="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      </div>
      <h3 class="text-xl font-bold text-emerald-900">Action Steps — Prepare and Send a Simple Invoice</h3>
    </div>
    
    <div class="space-y-4">
      
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">1</div>
        <div>
          <p class="font-semibold text-slate-900">Create Your Product</p>
          <p class="text-slate-600 text-sm">Go to Payments → Products and create your service product with a clear name and description.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">2</div>
        <div>
          <p class="font-semibold text-slate-900">Set the Price</p>
          <p class="text-slate-600 text-sm">Add a one-time price with the correct amount and currency.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">3</div>
        <div>
          <p class="font-semibold text-slate-900">Save and Verify</p>
          <p class="text-slate-600 text-sm">Save the product, reopen it, and check all details are correct.</p>
        </div>
      </div>
    </div>
  </div>
</div>',
      true,
      3,
      NOW(),
      NOW()
    )
    RETURNING id INTO v_lesson_id;
    
    RAISE NOTICE 'Created lesson: Create a Simple Product';
  ELSE
    -- Update existing lesson
    UPDATE public.lessons 
    SET 
      content = '<div class="space-y-8">
  <!-- Learning Goal -->
  <div class="bg-gradient-to-r from-amber-500 to-orange-500 rounded-2xl p-6 text-white shadow-lg">
    <div class="flex items-center gap-3 mb-3">
      <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-lg font-bold">Learning Goal</h3>
    </div>
    <p class="text-white/90 text-lg">Create a reusable one-time service product with a clear name, description, and price.</p>
  </div>

  <!-- Step 1: Open Products -->
  <div class="bg-gradient-to-br from-slate-50 to-blue-50 rounded-2xl p-6 border border-blue-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 1: Open Products</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Navigate to Products</h4>
          <p class="text-sm text-slate-600">Go to Payments → Products. Select Create Product. Choose the standard product option.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Step 2: Add Product Information -->
  <div class="bg-gradient-to-br from-slate-50 to-cyan-50 rounded-2xl p-6 border border-cyan-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-cyan-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 2: Add Product Information</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Name and Description</h4>
          <p class="text-sm text-slate-600">Name: 90-Minute Strategy Session. Description: A focused 90-minute session to review one business challenge and agree on the next actions.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Image (Optional)</h4>
          <p class="text-sm text-slate-600">Add an image only if it helps the buyer recognize the offer.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Keep Names Clear</h4>
          <p class="text-sm text-slate-600">Avoid internal codes or vague labels that a buyer will not understand.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Step 3: Add the Price -->
  <div class="bg-gradient-to-br from-slate-50 to-green-50 rounded-2xl p-6 border border-green-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 3: Add the Price</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Price Settings</h4>
          <p class="text-sm text-slate-600">Payment type: One-time. Amount: $495.00 (or your selected price). Currency: The currency used by the connected account.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Recurring Prices</h4>
          <p class="text-sm text-slate-600">Create recurring prices only after deciding billing frequency, start date, cancellation terms, and what the customer receives each period.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Step 4: Review and Save -->
  <div class="bg-gradient-to-br from-slate-50 to-green-50 rounded-2xl p-6 border border-green-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Step 4: Review and Save</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Optional Settings</h4>
          <p class="text-sm text-slate-600">Check taxes, product statement description, quantity, online-store visibility, inventory (if physical item).</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Don''t Enable Unnecessary Settings</h4>
          <p class="text-sm text-slate-600">Do not turn on a setting simply because it is available. It should match how this offer is sold and delivered.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Save and Inspect</h4>
          <p class="text-sm text-slate-600">Save the product, then reopen it and verify: name is correct, description is clear, amount and currency are correct, price is one-time, tax settings match, product is active.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Naming Examples -->
  <div class="bg-gradient-to-br from-slate-50 to-amber-50 rounded-2xl p-6 border border-amber-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Naming Examples</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Clear Names</h4>
          <p class="text-sm text-slate-600">Coach: Leadership Coaching Session — 60 Minutes. Consultant: Operations Review — Half Day. Speaker: Virtual Keynote — 45 Minutes.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Weak Names</h4>
          <p class="text-sm text-slate-600">Avoid vague names like: Coaching, Consulting Work, Speaking, Training, Plan A.</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Point -->
  <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-6 border-l-4 border-amber-400">
    <div class="flex items-start gap-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
      </div>
      <div>
        <h3 class="text-lg font-bold text-amber-900 mb-2">Key Point</h3>
        <p class="text-amber-800 text-lg">Create a clear, descriptive product with the correct price and payment type. Save and inspect before using it in invoices or payment links.</p>
      </div>
    </div>
  </div>

  <!-- Action Steps -->
  <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border-2 border-emerald-200">
    <div class="flex items-center gap-3 mb-5">
      <div class="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      </div>
      <h3 class="text-xl font-bold text-emerald-900">Action Steps — Prepare and Send a Simple Invoice</h3>
    </div>
    
    <div class="space-y-4">
      
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">1</div>
        <div>
          <p class="font-semibold text-slate-900">Create Your Product</p>
          <p class="text-slate-600 text-sm">Go to Payments → Products and create your service product with a clear name and description.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">2</div>
        <div>
          <p class="font-semibold text-slate-900">Set the Price</p>
          <p class="text-slate-600 text-sm">Add a one-time price with the correct amount and currency.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">3</div>
        <div>
          <p class="font-semibold text-slate-900">Save and Verify</p>
          <p class="text-slate-600 text-sm">Save the product, reopen it, and check all details are correct.</p>
        </div>
      </div>
    </div>
  </div>
</div>',
      title = 'Create a Simple Product',
      lesson_number = 3,
      sort_order = 3,
      updated_at = NOW()
    WHERE id = v_lesson_id;
    
    RAISE NOTICE 'Updated lesson: Create a Simple Product';
  END IF;

END $$;


-- Insert Quiz Questions for Lesson: Create a Simple Product

DO $$
DECLARE
  v_module_id UUID;
  v_lesson_id UUID;
  v_quiz_id UUID;
BEGIN
  -- Get Module by week number
  SELECT id INTO v_module_id FROM public.training_modules WHERE week_number = 11 LIMIT 1;
  
  IF v_module_id IS NULL THEN
    RAISE NOTICE 'Module 11 not found';
    RETURN;
  END IF;

  -- Get the lesson ID
  SELECT id INTO v_lesson_id 
  FROM public.lessons 
  WHERE slug = 'create-simple-product' AND module_id = v_module_id;
  
  IF v_lesson_id IS NULL THEN
    RAISE NOTICE 'Lesson create-simple-product not found in module 11';
    RETURN;
  END IF;
  
  -- Delete existing quizzes to avoid duplicates
  DELETE FROM public.lesson_quizzes WHERE lesson_id = v_lesson_id;


  -- Question 1
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'Why should a product be created before a payment link?', 
    '["Payment links are not necessary","The payment link needs a saved product and price to display what the buyer is purchasing","Products automatically create payment links","Invoices do not need products"]'::jsonb,
    'The payment link needs a saved product and price to display what the buyer is purchasing',
    'A payment link needs a saved product and price to display what the buyer is purchasing and how much they will pay. The product must exist first.', 
    1
  )
  RETURNING id INTO v_quiz_id;


  -- Question 2
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'What makes a good product name?', 
    '["Internal codes like PRD-001","Clear, descriptive names buyers understand like ''Leadership Coaching Session — 60 Minutes''","Vague labels like ''Coaching'' or ''Plan A''","Random numbers and letters"]'::jsonb,
    'Clear, descriptive names buyers understand like ''Leadership Coaching Session — 60 Minutes''',
    'Good product names are clear and descriptive so buyers understand what they are purchasing. Avoid internal codes and vague labels.', 
    2
  )
  RETURNING id INTO v_quiz_id;


  -- Question 3
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'What should you check after saving a product?', 
    '["Nothing, it is automatically correct","Name, description, amount, currency, payment type, tax settings, and availability","Only the product image","Just the creation date"]'::jsonb,
    'Name, description, amount, currency, payment type, tax settings, and availability',
    'After saving, reopen the product and verify: name is correct, description is clear, amount and currency are correct, price is one-time (if intended), tax settings match, and product is active.', 
    3
  )
  RETURNING id INTO v_quiz_id;

END $$;
