-- Lesson 6: What Happens After Submit
-- Module 7: Forms: Capturing Leads the Right Way
-- Generated by Course Content Creator Skill

-- Insert/Update Lesson 6: What Happens After Submit
-- Module 7: Forms: Capturing Leads the Right Way
-- Using color blocks, icons, horizontal cards, and better visual hierarchy

DO $$
DECLARE
  v_module_id UUID;
  v_lesson_id UUID;
BEGIN
  -- Get Module by week number
  SELECT id INTO v_module_id FROM public.training_modules WHERE week_number = 7 LIMIT 1;
  
  IF v_module_id IS NULL THEN
    RAISE NOTICE 'Module 7 not found';
    RETURN;
  END IF;

  -- Check if lesson exists
  SELECT id INTO v_lesson_id 
  FROM public.lessons 
  WHERE slug = 'what-happens-after-submit' AND module_id = v_module_id;
  
  IF v_lesson_id IS NULL THEN
    -- Insert new lesson
    INSERT INTO public.lessons (
      module_id, 
      lesson_number, 
      title, 
      slug, 
      content, 
      is_published, 
      sort_order,
      created_at,
      updated_at
    ) VALUES (
      v_module_id,
      6,
      'What Happens After Submit',
      'what-happens-after-submit',
      '<div class="space-y-8">
  <!-- Learning Goal -->
  <div class="bg-gradient-to-r from-amber-500 to-orange-500 rounded-2xl p-6 text-white shadow-lg">
    <div class="flex items-center gap-3 mb-3">
      <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-lg font-bold">Learning Goal</h3>
    </div>
    <p class="text-white/90 text-lg">Learn how to set up automated follow-up actions when someone submits a form.</p>
  </div>

  <!-- The Follow-Up Process -->
  <div class="bg-gradient-to-br from-slate-50 to-blue-50 rounded-2xl p-6 border border-blue-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">The Follow-Up Process</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">1. Contact Created or Updated</h4>
          <p class="text-sm text-slate-600">LeadProspectrr automatically creates a new contact or updates an existing one.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-cyan-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">2. Tag Added</h4>
          <p class="text-sm text-slate-600">Add a tag like ''New Lead - Consultation Request'' to organize and segment the lead.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">3. Internal Notification</h4>
          <p class="text-sm text-slate-600">Alert yourself or your team that a new lead has come in.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">4. Thank-You Email</h4>
          <p class="text-sm text-slate-600">Send a confirmation email to the lead so they know their request was received.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Advanced Actions -->
  <div class="bg-gradient-to-br from-slate-50 to-purple-50 rounded-2xl p-6 border border-purple-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center">
        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Advanced Actions</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">5. Add to Pipeline</h4>
          <p class="text-sm text-slate-600">Add the lead to the right pipeline stage if this is a sales or opportunity-based form.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-indigo-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">6. Start Workflow</h4>
          <p class="text-sm text-slate-600">Trigger an automation sequence for nurture, follow-up, or onboarding.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">7. Redirect to Next Step</h4>
          <p class="text-sm text-slate-600">Send the person to a thank-you page, booking calendar, or download page.</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Point -->
  <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-6 border-l-4 border-amber-400">
    <div class="flex items-start gap-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
      </div>
      <div>
        <h3 class="text-lg font-bold text-amber-900 mb-2">Key Point</h3>
        <p class="text-amber-800 text-lg">The form collects the lead. The follow-up turns that lead into a conversation. Set up automated actions so no lead sits unseen in an inbox.</p>
      </div>
    </div>
  </div>

  <!-- Action Steps -->
  <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border-2 border-emerald-200">
    <div class="flex items-center gap-3 mb-5">
      <div class="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      </div>
      <h3 class="text-xl font-bold text-emerald-900">Action Steps — Testing Your Form</h3>
    </div>
    
    <div class="space-y-4">
      
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">1</div>
        <div>
          <p class="font-semibold text-slate-900">Map Your Follow-Up</p>
          <p class="text-slate-600 text-sm">For each form, list what should happen after someone submits it.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">2</div>
        <div>
          <p class="font-semibold text-slate-900">Set Up Tags</p>
          <p class="text-slate-600 text-sm">Create clear tags for each form type so you can segment and track leads.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">3</div>
        <div>
          <p class="font-semibold text-slate-900">Configure Notifications</p>
          <p class="text-slate-600 text-sm">Make sure you or your team get alerted when new leads come in.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">4</div>
        <div>
          <p class="font-semibold text-slate-900">Create Thank-You Emails</p>
          <p class="text-slate-600 text-sm">Write simple confirmation emails that let leads know their request was received.</p>
        </div>
      </div>
    </div>
  </div>
</div>',
      true,
      6,
      NOW(),
      NOW()
    )
    RETURNING id INTO v_lesson_id;
    
    RAISE NOTICE 'Created lesson: What Happens After Submit';
  ELSE
    -- Update existing lesson
    UPDATE public.lessons 
    SET 
      content = '<div class="space-y-8">
  <!-- Learning Goal -->
  <div class="bg-gradient-to-r from-amber-500 to-orange-500 rounded-2xl p-6 text-white shadow-lg">
    <div class="flex items-center gap-3 mb-3">
      <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-lg font-bold">Learning Goal</h3>
    </div>
    <p class="text-white/90 text-lg">Learn how to set up automated follow-up actions when someone submits a form.</p>
  </div>

  <!-- The Follow-Up Process -->
  <div class="bg-gradient-to-br from-slate-50 to-blue-50 rounded-2xl p-6 border border-blue-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">The Follow-Up Process</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">1. Contact Created or Updated</h4>
          <p class="text-sm text-slate-600">LeadProspectrr automatically creates a new contact or updates an existing one.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-cyan-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">2. Tag Added</h4>
          <p class="text-sm text-slate-600">Add a tag like ''New Lead - Consultation Request'' to organize and segment the lead.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">3. Internal Notification</h4>
          <p class="text-sm text-slate-600">Alert yourself or your team that a new lead has come in.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">4. Thank-You Email</h4>
          <p class="text-sm text-slate-600">Send a confirmation email to the lead so they know their request was received.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Advanced Actions -->
  <div class="bg-gradient-to-br from-slate-50 to-purple-50 rounded-2xl p-6 border border-purple-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center">
        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Advanced Actions</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">5. Add to Pipeline</h4>
          <p class="text-sm text-slate-600">Add the lead to the right pipeline stage if this is a sales or opportunity-based form.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-indigo-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">6. Start Workflow</h4>
          <p class="text-sm text-slate-600">Trigger an automation sequence for nurture, follow-up, or onboarding.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">7. Redirect to Next Step</h4>
          <p class="text-sm text-slate-600">Send the person to a thank-you page, booking calendar, or download page.</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Point -->
  <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-6 border-l-4 border-amber-400">
    <div class="flex items-start gap-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
      </div>
      <div>
        <h3 class="text-lg font-bold text-amber-900 mb-2">Key Point</h3>
        <p class="text-amber-800 text-lg">The form collects the lead. The follow-up turns that lead into a conversation. Set up automated actions so no lead sits unseen in an inbox.</p>
      </div>
    </div>
  </div>

  <!-- Action Steps -->
  <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border-2 border-emerald-200">
    <div class="flex items-center gap-3 mb-5">
      <div class="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      </div>
      <h3 class="text-xl font-bold text-emerald-900">Action Steps — Testing Your Form</h3>
    </div>
    
    <div class="space-y-4">
      
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">1</div>
        <div>
          <p class="font-semibold text-slate-900">Map Your Follow-Up</p>
          <p class="text-slate-600 text-sm">For each form, list what should happen after someone submits it.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">2</div>
        <div>
          <p class="font-semibold text-slate-900">Set Up Tags</p>
          <p class="text-slate-600 text-sm">Create clear tags for each form type so you can segment and track leads.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">3</div>
        <div>
          <p class="font-semibold text-slate-900">Configure Notifications</p>
          <p class="text-slate-600 text-sm">Make sure you or your team get alerted when new leads come in.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">4</div>
        <div>
          <p class="font-semibold text-slate-900">Create Thank-You Emails</p>
          <p class="text-slate-600 text-sm">Write simple confirmation emails that let leads know their request was received.</p>
        </div>
      </div>
    </div>
  </div>
</div>',
      title = 'What Happens After Submit',
      lesson_number = 6,
      sort_order = 6,
      updated_at = NOW()
    WHERE id = v_lesson_id;
    
    RAISE NOTICE 'Updated lesson: What Happens After Submit';
  END IF;

END $$;


-- Insert Quiz Questions for Lesson: What Happens After Submit

DO $$
DECLARE
  v_module_id UUID;
  v_lesson_id UUID;
  v_quiz_id UUID;
BEGIN
  -- Get Module by week number
  SELECT id INTO v_module_id FROM public.training_modules WHERE week_number = 7 LIMIT 1;
  
  IF v_module_id IS NULL THEN
    RAISE NOTICE 'Module 7 not found';
    RETURN;
  END IF;

  -- Get the lesson ID
  SELECT id INTO v_lesson_id 
  FROM public.lessons 
  WHERE slug = 'what-happens-after-submit' AND module_id = v_module_id;
  
  IF v_lesson_id IS NULL THEN
    RAISE NOTICE 'Lesson what-happens-after-submit not found in module 7';
    RETURN;
  END IF;
  
  -- Delete existing quizzes to avoid duplicates
  DELETE FROM public.lesson_quizzes WHERE lesson_id = v_lesson_id;


  -- Question 1
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'What should happen after someone submits a form?', 
    '["Nothing, the form just stores the data","Contact creation, tagging, notifications, thank-you emails, pipeline entry, and workflows","Delete the submission","Send a bill"]'::jsonb,
    'Contact creation, tagging, notifications, thank-you emails, pipeline entry, and workflows',
    'After form submission, LeadProspectrr can create contacts, add tags, send notifications and emails, add to pipelines, start workflows, and redirect to next steps.', 
    1
  )
  RETURNING id INTO v_quiz_id;


  -- Question 2
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'Why should you add a tag when someone submits a form?', 
    '["Tags are required by law","To organize leads by interest and know where they came from","To delete the lead later","To charge them money"]'::jsonb,
    'To organize leads by interest and know where they came from',
    'Tags help you organize leads by interest, track where they came from, and segment them for appropriate follow-up.', 
    2
  )
  RETURNING id INTO v_quiz_id;


  -- Question 3
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'Why is a thank-you email important?', 
    '["It is required by law","People like to know their request was received and what happens next","It sells products immediately","It deletes the form submission"]'::jsonb,
    'People like to know their request was received and what happens next',
    'A thank-you email confirms the submission was received, sets expectations for follow-up, and starts building trust with the lead.', 
    3
  )
  RETURNING id INTO v_quiz_id;

END $$;
