-- Lesson 7: Moving Leads Through the Pipeline
-- Module 5: Opportunities and Pipelines
-- Generated by Course Content Creator Skill

-- Insert/Update Lesson 7: Moving Leads Through the Pipeline
-- Module 5: Opportunities and Pipelines
-- Using color blocks, icons, horizontal cards, and better visual hierarchy

DO $$
DECLARE
  v_module_id UUID;
  v_lesson_id UUID;
BEGIN
  -- Get Module by week number
  SELECT id INTO v_module_id FROM public.training_modules WHERE week_number = 5 LIMIT 1;
  
  IF v_module_id IS NULL THEN
    RAISE NOTICE 'Module 5 not found';
    RETURN;
  END IF;

  -- Check if lesson exists
  SELECT id INTO v_lesson_id 
  FROM public.lessons 
  WHERE slug = 'moving-leads-pipeline' AND module_id = v_module_id;
  
  IF v_lesson_id IS NULL THEN
    -- Insert new lesson
    INSERT INTO public.lessons (
      module_id, 
      lesson_number, 
      title, 
      slug, 
      content, 
      is_published, 
      sort_order,
      created_at,
      updated_at
    ) VALUES (
      v_module_id,
      7,
      'Moving Leads Through the Pipeline',
      'moving-leads-pipeline',
      '<div class="space-y-8">
  <!-- Learning Goal -->
  <div class="bg-gradient-to-r from-amber-500 to-orange-500 rounded-2xl p-6 text-white shadow-lg">
    <div class="flex items-center gap-3 mb-3">
      <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-lg font-bold">Learning Goal</h3>
    </div>
    <p class="text-white/90 text-lg">Learn how and when to move an Opportunity from one stage to another.</p>
  </div>

  <!-- When to Move Leads -->
  <div class="bg-gradient-to-br from-slate-50 to-blue-50 rounded-2xl p-6 border border-blue-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">When to Move Leads</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Move When Something Changes</h4>
          <p class="text-sm text-slate-600">A lead should move when something changes. Contacted them? Move to Contacted. They booked a call? Move to Appointment Booked. Sent proposal? Move to Proposal Sent. They said yes? Move to Won. Not moving forward? Move to Lost.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Example: Sarah''s Journey -->
  <div class="bg-gradient-to-br from-slate-50 to-green-50 rounded-2xl p-6 border border-green-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Example: Sarah''s Journey</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">1. New Lead</h4>
          <p class="text-sm text-slate-600">Sarah asked about a website redesign.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-cyan-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">2. Contacted</h4>
          <p class="text-sm text-slate-600">You replied and asked her to book a call.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">3. Appointment Booked</h4>
          <p class="text-sm text-slate-600">Sarah booked a discovery call.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">4. Proposal Sent</h4>
          <p class="text-sm text-slate-600">You sent her the website proposal.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">5. Won</h4>
          <p class="text-sm text-slate-600">Sarah accepted and paid the deposit.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Why This Matters -->
  <div class="bg-gradient-to-br from-slate-50 to-amber-50 rounded-2xl p-6 border border-amber-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Why This Matters</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Visual Clarity</h4>
          <p class="text-sm text-slate-600">Moving cards through the pipeline helps you avoid guessing. You can look at the board and know what needs attention.</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Point -->
  <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-6 border-l-4 border-amber-400">
    <div class="flex items-start gap-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
      </div>
      <div>
        <h3 class="text-lg font-bold text-amber-900 mb-2">Key Point</h3>
        <p class="text-amber-800 text-lg">Move the Opportunity card whenever the sales status changes. This keeps your pipeline accurate and shows you exactly what needs attention.</p>
      </div>
    </div>
  </div>

  <!-- Action Steps -->
  <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border-2 border-emerald-200">
    <div class="flex items-center gap-3 mb-5">
      <div class="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      </div>
      <h3 class="text-xl font-bold text-emerald-900">Action Steps — Adding Notes and Next Steps</h3>
    </div>
    
    <div class="space-y-4">
      
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">1</div>
        <div>
          <p class="font-semibold text-slate-900">Review Current Opportunities</p>
          <p class="text-slate-600 text-sm">Look at your Opportunities and identify which ones need to move stages.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">2</div>
        <div>
          <p class="font-semibold text-slate-900">Move One Lead</p>
          <p class="text-slate-600 text-sm">Take one example lead and move them to the correct stage based on what has happened.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">3</div>
        <div>
          <p class="font-semibold text-slate-900">Update Notes</p>
          <p class="text-slate-600 text-sm">Add a note about why you moved them and what happened.</p>
        </div>
      </div>
    </div>
  </div>
</div>',
      true,
      7,
      NOW(),
      NOW()
    )
    RETURNING id INTO v_lesson_id;
    
    RAISE NOTICE 'Created lesson: Moving Leads Through the Pipeline';
  ELSE
    -- Update existing lesson
    UPDATE public.lessons 
    SET 
      content = '<div class="space-y-8">
  <!-- Learning Goal -->
  <div class="bg-gradient-to-r from-amber-500 to-orange-500 rounded-2xl p-6 text-white shadow-lg">
    <div class="flex items-center gap-3 mb-3">
      <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-lg font-bold">Learning Goal</h3>
    </div>
    <p class="text-white/90 text-lg">Learn how and when to move an Opportunity from one stage to another.</p>
  </div>

  <!-- When to Move Leads -->
  <div class="bg-gradient-to-br from-slate-50 to-blue-50 rounded-2xl p-6 border border-blue-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">When to Move Leads</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Move When Something Changes</h4>
          <p class="text-sm text-slate-600">A lead should move when something changes. Contacted them? Move to Contacted. They booked a call? Move to Appointment Booked. Sent proposal? Move to Proposal Sent. They said yes? Move to Won. Not moving forward? Move to Lost.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Example: Sarah''s Journey -->
  <div class="bg-gradient-to-br from-slate-50 to-green-50 rounded-2xl p-6 border border-green-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Example: Sarah''s Journey</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">1. New Lead</h4>
          <p class="text-sm text-slate-600">Sarah asked about a website redesign.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-cyan-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">2. Contacted</h4>
          <p class="text-sm text-slate-600">You replied and asked her to book a call.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">3. Appointment Booked</h4>
          <p class="text-sm text-slate-600">Sarah booked a discovery call.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">4. Proposal Sent</h4>
          <p class="text-sm text-slate-600">You sent her the website proposal.</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">5. Won</h4>
          <p class="text-sm text-slate-600">Sarah accepted and paid the deposit.</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Why This Matters -->
  <div class="bg-gradient-to-br from-slate-50 to-amber-50 rounded-2xl p-6 border border-amber-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Why This Matters</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Visual Clarity</h4>
          <p class="text-sm text-slate-600">Moving cards through the pipeline helps you avoid guessing. You can look at the board and know what needs attention.</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Point -->
  <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-6 border-l-4 border-amber-400">
    <div class="flex items-start gap-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
      </div>
      <div>
        <h3 class="text-lg font-bold text-amber-900 mb-2">Key Point</h3>
        <p class="text-amber-800 text-lg">Move the Opportunity card whenever the sales status changes. This keeps your pipeline accurate and shows you exactly what needs attention.</p>
      </div>
    </div>
  </div>

  <!-- Action Steps -->
  <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border-2 border-emerald-200">
    <div class="flex items-center gap-3 mb-5">
      <div class="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      </div>
      <h3 class="text-xl font-bold text-emerald-900">Action Steps — Adding Notes and Next Steps</h3>
    </div>
    
    <div class="space-y-4">
      
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">1</div>
        <div>
          <p class="font-semibold text-slate-900">Review Current Opportunities</p>
          <p class="text-slate-600 text-sm">Look at your Opportunities and identify which ones need to move stages.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">2</div>
        <div>
          <p class="font-semibold text-slate-900">Move One Lead</p>
          <p class="text-slate-600 text-sm">Take one example lead and move them to the correct stage based on what has happened.</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">3</div>
        <div>
          <p class="font-semibold text-slate-900">Update Notes</p>
          <p class="text-slate-600 text-sm">Add a note about why you moved them and what happened.</p>
        </div>
      </div>
    </div>
  </div>
</div>',
      title = 'Moving Leads Through the Pipeline',
      lesson_number = 7,
      sort_order = 7,
      updated_at = NOW()
    WHERE id = v_lesson_id;
    
    RAISE NOTICE 'Updated lesson: Moving Leads Through the Pipeline';
  END IF;

END $$;


-- Insert Quiz Questions for Lesson: Moving Leads Through the Pipeline

DO $$
DECLARE
  v_module_id UUID;
  v_lesson_id UUID;
  v_quiz_id UUID;
BEGIN
  -- Get Module by week number
  SELECT id INTO v_module_id FROM public.training_modules WHERE week_number = 5 LIMIT 1;
  
  IF v_module_id IS NULL THEN
    RAISE NOTICE 'Module 5 not found';
    RETURN;
  END IF;

  -- Get the lesson ID
  SELECT id INTO v_lesson_id 
  FROM public.lessons 
  WHERE slug = 'moving-leads-pipeline' AND module_id = v_module_id;
  
  IF v_lesson_id IS NULL THEN
    RAISE NOTICE 'Lesson moving-leads-pipeline not found in module 5';
    RETURN;
  END IF;
  
  -- Delete existing quizzes to avoid duplicates
  DELETE FROM public.lesson_quizzes WHERE lesson_id = v_lesson_id;


  -- Question 1
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'When should you move a lead to the ''Contacted'' stage?', 
    '["When they first show interest","When you have replied, called, texted, or emailed them","When they pay","Never"]'::jsonb,
    'When you have replied, called, texted, or emailed them',
    'Move a lead to Contacted when you have actively reached out to them - by replying, calling, texting, or emailing. This shows the lead has been contacted, not just that they showed interest.', 
    1
  )
  RETURNING id INTO v_quiz_id;


  -- Question 2
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'Why is moving leads through the pipeline important?', 
    '["It makes the board look colorful","It helps you avoid guessing and know what needs attention","It is required by law","It deletes old leads"]'::jsonb,
    'It helps you avoid guessing and know what needs attention',
    'Moving leads through the pipeline gives you visual clarity. You can look at the board and immediately know what needs attention - who is new, who has been contacted, who needs a proposal, etc.', 
    2
  )
  RETURNING id INTO v_quiz_id;


  -- Question 3
  INSERT INTO public.lesson_quizzes (lesson_id, question, options, correct_answer, explanation, sort_order)
  VALUES (
    v_lesson_id, 
    'What should you do when a lead says yes to your offer?', 
    '["Delete the Opportunity","Move them to the ''Won'' stage","Leave them in ''New Lead''","Move them to ''Lost''"]'::jsonb,
    'Move them to the ''Won'' stage',
    'When a lead agrees to move forward and becomes a client, move them to the ''Won'' stage. This tracks your successful conversions and clears them from active follow-up stages.', 
    3
  )
  RETURNING id INTO v_quiz_id;

END $$;
