-- Lesson 8: Save the Smart List
-- Module 2: Contacts and Smart Lists
-- Generated by Course Content Creator Skill

-- Update Lesson 8: Save the Smart List
-- Module 2: Contacts and Smart Lists
-- Using color blocks, icons, horizontal cards, and better visual hierarchy

DO $$
DECLARE
  v_module_id UUID;
BEGIN
  -- Get Module by week number
  SELECT id INTO v_module_id FROM public.training_modules WHERE week_number = 2 LIMIT 1;
  
  IF v_module_id IS NULL THEN
    RAISE NOTICE 'Module 2 not found';
    RETURN;
  END IF;

  UPDATE public.lessons 
  SET content = '<div class="space-y-8">
  <!-- Learning Goal -->
  <div class="bg-gradient-to-r from-amber-500 to-orange-500 rounded-2xl p-6 text-white shadow-lg">
    <div class="flex items-center gap-3 mb-3">
      <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center">
        <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
      </div>
      <h3 class="text-lg font-bold">Learning Goal</h3>
    </div>
    <p class="text-white/90 text-lg">Save a filtered view so it can be used again later.</p>
  </div>

  <!-- Steps to Save -->
  <div class="bg-gradient-to-br from-slate-50 to-purple-50 rounded-2xl p-6 border border-purple-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Steps to Save</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Step 1</h4>
          <p class="text-sm text-slate-600">Build your filters</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Step 2</h4>
          <p class="text-sm text-slate-600">Review the contacts shown</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-purple-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Step 3</h4>
          <p class="text-sm text-slate-600">Click Save as Smart List</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Step 4</h4>
          <p class="text-sm text-slate-600">Give the list a clear name</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Step 5</h4>
          <p class="text-sm text-slate-600">Save it</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-cyan-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Step 6</h4>
          <p class="text-sm text-slate-600">Reopen it later when needed</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Good Smart List Names -->
  <div class="bg-gradient-to-br from-slate-50 to-green-50 rounded-2xl p-6 border border-green-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center">
        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Good Smart List Names</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">New Leads — Last 30 Days</h4>
          <p class="text-sm text-slate-600">Clear and specific</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Hot Leads — Need Follow-Up</h4>
          <p class="text-sm text-slate-600">Shows status and action needed</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Leads — No Appointment Booked</h4>
          <p class="text-sm text-slate-600">Specific criteria and purpose</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-green-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Clients — Active</h4>
          <p class="text-sm text-slate-600">Simple and clear</p>
        </div>
      </div>
    </div>
  </div>
  <!-- Weak Smart List Names -->
  <div class="bg-gradient-to-br from-slate-50 to-rose-50 rounded-2xl p-6 border border-rose-100">
    <div class="flex items-center gap-3 mb-4">
      <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
      </div>
      <h3 class="text-xl font-bold text-slate-900">Weak Smart List Names</h3>
    </div>
    
    <div class="space-y-3">
      
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">List 1</h4>
          <p class="text-sm text-slate-600">Too vague - doesn''t explain what it contains</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Test</h4>
          <p class="text-sm text-slate-600">Not descriptive - temporary name that stayed</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Follow-Up</h4>
          <p class="text-sm text-slate-600">Too general - which follow-up?</p>
        </div>
      </div>
      <div class="flex items-center gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-12 h-12 rounded-xl bg-rose-100 flex items-center justify-center flex-shrink-0">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>
        </div>
        <div>
          <h4 class="font-semibold text-slate-900">Contacts</h4>
          <p class="text-sm text-slate-600">Not helpful - all contacts are contacts</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Key Point -->
  <div class="bg-gradient-to-r from-amber-50 to-orange-50 rounded-2xl p-6 border-l-4 border-amber-400">
    <div class="flex items-start gap-4">
      <div class="w-12 h-12 rounded-xl bg-amber-100 flex items-center justify-center flex-shrink-0">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg>
      </div>
      <div>
        <h3 class="text-lg font-bold text-amber-900 mb-2">Key Point</h3>
        <p class="text-amber-800 text-lg">A clear Smart List name saves time later. You should know what the list does just by reading the name.</p>
      </div>
    </div>
  </div>

  <!-- Action Steps -->
  <div class="bg-gradient-to-br from-emerald-50 to-teal-50 rounded-2xl p-6 border-2 border-emerald-200">
    <div class="flex items-center gap-3 mb-5">
      <div class="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4"/></svg>
      </div>
      <h3 class="text-xl font-bold text-emerald-900">Action Steps — Use Your Smart List</h3>
    </div>
    
    <div class="space-y-4">
      
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">1</div>
        <div>
          <p class="font-semibold text-slate-900">Build your filters</p>
          <p class="text-slate-600 text-sm">Get the right contacts showing</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">2</div>
        <div>
          <p class="font-semibold text-slate-900">Click Save as Smart List</p>
          <p class="text-slate-600 text-sm">Start the save process</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">3</div>
        <div>
          <p class="font-semibold text-slate-900">Use a clear name</p>
          <p class="text-slate-600 text-sm">Name it so you know what it does at a glance</p>
        </div>
      </div>
      <div class="flex items-start gap-4 bg-white rounded-xl p-4 shadow-sm">
        <div class="w-10 h-10 rounded-full bg-emerald-500 text-white flex items-center justify-center font-bold text-lg flex-shrink-0">4</div>
        <div>
          <p class="font-semibold text-slate-900">Save and test</p>
          <p class="text-slate-600 text-sm">Save it and reopen to verify it works</p>
        </div>
      </div>
    </div>
  </div>
</div>'
  WHERE slug = 'save-smart-list' AND module_id = v_module_id;

END $$;


-- Insert Quiz Questions for Lesson: Save the Smart List

DO $$
DECLARE
  v_lesson_id UUID;
  v_quiz_id UUID;
BEGIN
  -- Get the lesson ID
  SELECT id INTO v_lesson_id 
  FROM public.lessons 
  WHERE slug = 'save-smart-list';
  
  IF v_lesson_id IS NULL THEN
    RAISE NOTICE 'Lesson save-smart-list not found';
    RETURN;
  END IF;


  -- Question 1
  INSERT INTO public.lesson_quizzes (lesson_id, question, explanation, sort_order)
  VALUES (v_lesson_id, 'Why should Smart List names be clear?', 'Clear names like ''Hot Leads — Need Follow-Up'' tell you exactly what the list contains and when to use it, saving time and preventing confusion.', 1)
  RETURNING id INTO v_quiz_id;

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'They don''t need to be clear', false, 1);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Clear names help you quickly understand what the list shows and when to use it', true, 2);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Only admins see the names', false, 3);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Names are just for decoration', false, 4);


  -- Question 2
  INSERT INTO public.lesson_quizzes (lesson_id, question, explanation, sort_order)
  VALUES (v_lesson_id, 'Which is an example of a GOOD Smart List name?', '''Hot Leads — Need Follow-Up'' is clear and specific, telling you exactly what the list contains and what action to take.', 2)
  RETURNING id INTO v_quiz_id;

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'List 1', false, 1);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Test', false, 2);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Hot Leads — Need Follow-Up', true, 3);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Contacts', false, 4);


  -- Question 3
  INSERT INTO public.lesson_quizzes (lesson_id, question, explanation, sort_order)
  VALUES (v_lesson_id, 'What should you do after saving a Smart List?', 'After saving, you should reopen the Smart List to verify it shows the correct contacts and works as expected.', 3)
  RETURNING id INTO v_quiz_id;

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Never use it again', false, 1);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Reopen it to verify it works correctly', true, 2);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Delete it immediately', false, 3);

  INSERT INTO public.lesson_quiz_options (quiz_id, option_text, is_correct, sort_order)
  VALUES (v_quiz_id, 'Tell everyone not to use it', false, 4);

END $$;
